apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ledgerlens.fullname" . }}
  labels:
    {{- include "ledgerlens.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.secrets.LEDGERLENS_SERVICE_SECRET_KEY }}
  LEDGERLENS_SERVICE_SECRET_KEY: {{ .Values.secrets.LEDGERLENS_SERVICE_SECRET_KEY | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.LEDGERLENS_MODEL_SIGNING_KEY }}
  LEDGERLENS_MODEL_SIGNING_KEY: {{ .Values.secrets.LEDGERLENS_MODEL_SIGNING_KEY | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.LEDGERLENS_ADMIN_API_KEY }}
  LEDGERLENS_ADMIN_API_KEY: {{ .Values.secrets.LEDGERLENS_ADMIN_API_KEY | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.LEDGERLENS_COMPLIANCE_API_KEY }}
  LEDGERLENS_COMPLIANCE_API_KEY: {{ .Values.secrets.LEDGERLENS_COMPLIANCE_API_KEY | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.LEDGERLENS_WEBHOOK_ENCRYPTION_KEY }}
  LEDGERLENS_WEBHOOK_ENCRYPTION_KEY: {{ .Values.secrets.LEDGERLENS_WEBHOOK_ENCRYPTION_KEY | b64enc | quote }}
  {{- end }}
